### ISSUE TITLE
Pre-Demo Checklist

### ISSUE THREAD

**Issue by Woolfrey** [hsp-iit/project-ergocub#132]
We need to develop a checklist to follow when starting up the ergoCub before a demo. This should include:
- A standard sequence of actions to take
- What to test to ensure the code is functioning correctly
- What to do if a test fails
- A list of last-working commits for dependent repositories

Once it is approved we should add the checklist to a README file in the project repository.

**Comment by xEnVrE** [comment]
> A list of last-working commits for dependent repositories

Can I suggest making a GitHub `release` of all the repositories so that we have a version tag instead of bare commits? What do you think?

**Comment by vigisushrutha23** [comment]
I have added a tag to the last working @Woolfrey/ergocub-bimanual tested on ErgocubSN000  [19cf08a](https://github.com/Woolfrey/ergocub-bimanual/commit/19cf08aa12bb0b00f5cc64e33382bf41b4762373) . We can use this as a fallback if it fails to function again (hopefully it won't happen). We will need to add actions required by @andrearosasco and @steb6 later as we did not test this.

**Comment by SimoneMic** [comment]
I have a rough idea of an hypothetical checklist or things that could be useful:
### Code
- [ ]  Use versions (0.1, 0.2, X.Y and so on) for each used module
- [ ]  Check dependencies (could be done automatically when building code using CMake, as example, by having a repo container "superbuild"-like that compiles and installs all the necessary components)
- [ ] Keep different demo stages based on complexity, so that it should always work straight out of the box.
### Organization
- [ ] Use the appropriate robot channel on Teams to communicate with other teams the upcoming demo (ASAP)
- [ ] Test the demo in a short time window before the show, but preferably not the day before.
- [ ] Book additional Robot slots for the demo test and demo showcase
- [ ] Have a fallback video in case of an hardware failure on the demo day
### Environment
- [ ] Check demo location status to be ready for the demo day (order, clean, other experiments not disturbing the demo ...)
- [ ] If navigation: Is it needed to map the environment? if yes, do it and test it some days before.
